stages:
# 依赖 redis 部署
- name: Redis
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:library-redis
      version: 3.0.2
      answers:
        master.persistence.enabled: "true"
        cluster.slaveCount: "2"
      name: redis
      targetNamespace: api
# 配置部署
- name: Config
  steps:
  - applyYamlConfig:
      path: ./config.yaml
# rpc 接口部署
- name: Micro
  steps:
  - applyYamlConfig:
      path: ./app/micro-api.yaml

